packages:
  - apps/**
  - packages/**
  - server/**

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@parcel/watcher'
  - bcrypt
  - core-js
  - core-js-pure
  - cypress
  - es5-ext
  - esbuild
  - nx
  - protobufjs
  - tsparticles-engine
