export const getColumnsMustHave = () => {
    return [
        'Matricule Paye',
        'Nom',
        'Prénom',
        'Département/Service',
        'Poste',
        'Type de contrat',
        "Date d'embauche",
        'Date fin PE 1',
        'Situation contrat',
        'Statut',
        'Manager N+1',
        'Nom + 1 ',
        'Manager N+2',
        'Nom N+2',
        'Genre ',
        'Date de naissance',
        'Lieu de naissance',
        'Adresse',
        'Nationalité',
        'CIN',
        'Carte de séjour',
        'Type',
        'Date de délivance CIN',
        'Lieu de délivrance',
        'Date de validité',
        "Autorisation d'emploi",
        "Déclaration d'Embauche CNAPS",
        "Déclaration d'embauche SMIE ",
        'Numéro CNAPS',
        'Situation matrimoniale',
        "Nombre d'enfants"
      ]
}